RandomChat/Controllers/ChatController.cs
using Amazon;
using Amazon.S3;
using Amazon.S3.Transfer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using RandomChat.Data;
using RandomChat.Models;
using RandomChat.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;


namespace RandomChat.Controllers
{
    public class ChatController : Controller
    {
        private readonly ChatContext _context;
        private ChatManger chatManger;
        private readonly IS3Service _service;

        public ChatController(ChatContext context, IS3Service service)
        {
            _context = context;
            chatManger = ChatManger.getInstance();
            _service = service;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32(nameof(AppUser.UserID)) == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.city = HttpContext.Session.GetString("city");
                return View();
            }
        }

        public async Task<IActionResult> List(int? id)
        {
            Topic topic = _context.Topics.Find(id);
            var TopicItem = await chatManger.GetReply(id);
            ViewBag.replies = TopicItem.Items.OrderByDescending(e => e.ReplyOn);
            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Reply(int? TopicId, string content, IFormFile uploadImage)
        {  
            string imageKey = "empty";

            if (uploadImage != null) 
            {
                
                imageKey = Convert.ToString(Guid.NewGuid()) + "|"  + uploadImage.FileName;

                using (var stream = new MemoryStream())
                {
                    await uploadImage.CopyToAsync(stream);
                    var response = await _service.UploadFileAsync(APIStrings.S3BUCKETNAME, stream, imageKey);
                }
            }
            
               
            int? UserId = HttpContext.Session.GetInt32(nameof(AppUser.UserID));
            if (await chatManger.Send(TopicId, content, imageKey,UserId))
            {
                return RedirectToAction("List", new { id = TopicId });
            }
            else
            {
                ModelState.AddModelError("Error", "Error when insertting your comment.");
                return RedirectToAction("List", new { id = TopicId });
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(string TopicName)
        {

            int UserId = Convert.ToInt32(HttpContext.Session.GetInt32(nameof(AppUser.UserID)));
            string location = HttpContext.Session.GetString("city");
            if (UserId == 0 || TopicName == null)
            {
                ModelState.AddModelError("Error", "Error when inserting your topic.");
                return View();
            }

            Topic topic = new Topic { TopicName = "#" + TopicName, UserId = UserId, Location = location };
            try
            {
                _context.Topics.Add(topic);
                _context.SaveChanges();
            }
            catch (Exception)
            {
                ModelState.AddModelError("Error", "Error when inserting your topic. Your topic name might be token.");
            }
            return RedirectToAction("List", new { id = topic.TopicId });
        }


    }
}

RandomChat/Controllers/PostPartialController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RandomChat.Data;
using RandomChat.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RandomChat.Controllers
{
    public class PostPartialController : Controller
    {
        private readonly ChatContext _context;
        public static int PICKED = 5;
        public PostPartialController(ChatContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ReList()
        {
            string city = HttpContext.Session.GetString("city");

            int count = _context.Topics.Count();

            List<Topic> topics = _context.Topics.Where(e => e.Location == city).OrderBy(r => Guid.NewGuid()).Take(PICKED).ToList();


            return PartialView("_ReList", topics);
        }

        [HttpGet]
        public IActionResult Search(string content)
        {
            List<Topic> topics = _context.Topics.Where(e => e.TopicName.Contains(content) || e.Location.Contains(content)).ToList();

            return PartialView("_ReList", topics);
        }
    }
}

RandomChat/Views/Chat/Create.cshtml
@model RandomChat.Models.Topic

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="TopicName" class="control-label">Add a new topic</label>
                <input type="text" asp-for="TopicName" class="control-label" />
                <span asp-validation-for="TopicName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @Html.ValidationMessage("Error", new { @class = "text-danger" })
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
  
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

RandomChat/Views/Chat/Index.cshtml
@model IEnumerable<Topic>


    @{
    ViewData["Title"] = "Start Chatting";
    }
    <ul class="nav">
        <li class="nav-item">
            <a asp-action="Create">Create New</a>
        </li>
       
        <li class="nav-item" style="float:right;">
            <a id="btnRefresh">
                <span class="glyphicon glyphicon-refresh"></span>
            </a>
        </li>
    </ul>
    <div class="form-group">
        <form asp-action="Search" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="search" required>
            <a class="btn btn-outline-success my-2 my-sm-0" id="btnSearch">Search</a>
        </form>
    </div>
    <div class="form-group">
        <form asp-controller="PostPartial">
            <div id="loader" style="display:none;"></div>
            <div id="posts">

            </div>
        </form>
    </div>
    <script>
        function showPage() {
            document.getElementById("loader").style.display = "none";
            document.getElementById("posts").style.display = "block";
        }

        $.ajax({
            url: "/PostPartial/ReList",
            type: "GET",
            cache: false,
            async: true,
            success: function (response) {
                $("#posts").html(response)
            }
        });

        $(document).ready(function () {
            $("#btnRefresh").click(function () {
                document.getElementById("loader").style.display = "block";
                document.getElementById("posts").style.display = "none";
                setTimeout(showPage, 1000);
                $.ajax({
                    url: "/PostPartial/ReList",
                    type: "GET",
                    cache: false,
                    async: true,
                    success: function (response) {
                        $("#posts").html(response)
                    }
                });
            })
        });


        $("#btnSearch").click(function () {
            document.getElementById("loader").style.display = "block";
            document.getElementById("posts").style.display = "none";
            setTimeout(showPage, 1000);
            var content = document.getElementById('search').value;
            $.ajax({
                url: "/PostPartial/Search",
                type: "GET",
                data: {content : content},
                cache: false,
                async: true,
                success: function (response) {
                    $("#posts").html(response)
                }
            })
        }
       );
    </script>

RandomChat/Views/Chat/List.cshtml
@model RandomChat.Models.Topic
@using RandomChat.Models

@{
    ViewData["Title"] = "Topic replies";
}
    <div class="container">
        <div class="row">

            <div class="col-sm">
                
            </div>
            <div class="col-sm">
                <h1>@Html.DisplayFor(Model => Model.TopicName)</h1>
                <ul class="list-group list-group-flush">
                    @foreach (var reply in ViewBag.replies)
                    {
                        <li class="list-group-item">
                            <p> <h3>Anonymous:</h3> @Html.Raw(reply.Reply) on @reply.ReplyOn</p>

                            @if (reply.ImageKey != "empty")
                            {
                       
                            <img src=@ImageManger.GetInstance().GetReplyImageUrl(reply.ImageKey) style="max-height:200px;max-width:600px;"/>
                      
                            }
                        </li>
                    }
                </ul>
                <div class="topics-container">
                    <form asp-action="Reply" enctype="multipart/form-data">
                        <input type="file" name="uploadImage" id="uploadImage" class="form-control-file" onchange="PreviewImage();" />
                        <img id="uploadPreview" style="width: 100px; height: 100px;" />

                        <textarea name="content" placeholder="Leave some short and nice comment :)"></textarea>
                        <input type="hidden" name="TopicId" id="TopicId" value="@Html.DisplayFor(Model => Model.TopicId)" />
                        <button type="submit" value="submit" class="btn btn-primary">Submit</button>
                        @Html.ValidationMessage("Error", new { @class = "text-danger" })
                    </form>
                </div>
                </div>
                <div class="col-sm">
                    
                </div>
            </div>
        </div>
        @section Scripts {
            <script>

                "use strict";

                function AJAXSubmit(oFormElement) {
                    var oReq = new XMLHttpRequest();
                    oReq.onload = function (e) {
                        oFormElement.elements.namedItem("result").value =
                            'Result: ' + this.status + ' ' + this.statusText;
                    };
                    oReq.open("post", oFormElement.action);
                    oReq.send(new FormData(oFormElement));
                }

                function PreviewImage() {
                    var oFReader = new FileReader();
                    oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

                    oFReader.onload = function (oFREvent) {
                        document.getElementById("uploadPreview").src = oFREvent.target.result;
                    };
                };
            </script>
            <script>
                tinymce.init({
                    selector: 'textarea',
                    width: '1110',
                    plugins: ["placeholder"]
                });
                tinymce.PluginManager.add('placeholder', function (editor) {
                    editor.on('init', function () {
                        var label = new Label;
                        onBlur();
                        tinymce.DOM.bind(label.el, 'click', onFocus);
                        editor.on('focus', onFocus);
                        editor.on('blur', onBlur);
                        editor.on('change', onBlur);
                        editor.on('setContent', onBlur);
                        function onFocus() { if (!editor.settings.readonly === true) { label.hide(); } editor.execCommand('mceFocus', false); }
                        function onBlur() { if (editor.getContent() == '') { label.show(); } else { label.hide(); } }
                    });
                    var Label = function () {
                        var placeholder_text = editor.getElement().getAttribute("placeholder") || editor.settings.placeholder;
                        var placeholder_attrs = editor.settings.placeholder_attrs || { style: { position: 'absolute', top: '2px', left: 0, color: '#aaaaaa', padding: '.25%', margin: '5px', width: '80%', 'font-size': '17px !important;', overflow: 'hidden', 'white-space': 'pre-wrap' } };
                        var contentAreaContainer = editor.getContentAreaContainer();
                        tinymce.DOM.setStyle(contentAreaContainer, 'position', 'relative');
                        this.el = tinymce.DOM.add(contentAreaContainer, "label", placeholder_attrs, placeholder_text);
                    }
                    Label.prototype.hide = function () { tinymce.DOM.setStyle(this.el, 'display', 'none'); }
                    Label.prototype.show = function () { tinymce.DOM.setStyle(this.el, 'display', ''); }
                });


            </script>
            @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
        }